### ISSUE TITLE
Что такое случайная величина?

### ISSUE THREAD

**Issue by gnull** [avsmal/spbau-crypto#2]
https://github.com/avsmal/spbau-crypto/blob/014729820e52664a81a27b47f7825726dd1f64ae/spbau-crypto-theory.tex#L433-L437

@avsmal, отличается ли это определение чем-то от предыдущего?

Я не до конца понимаю, что мы называем "случайной величиной" в этом конспекте, и чем это понятие отличается от "распределения"? Кажется, что эти два термина используются более-менее взаимозаменяемо. Если это так, то определение по ссылке кажется ненужным, а если не так, то непонятно, что это определение вообще должно значить.

Я раньше думал, что "распределением" мы называем любую функцию µ : A → [0, 1], задающую вероятности на конечном множестве элементарных событий A. А "случайные величины" — это функции f, g : A → V, из множества элементарных событий A во множество своих значений V. И когда всё понимается так, как я описал, распределения можно указывать под символом Pr, а случайные величины можно использовать в скобочках после Pr, например можно написать `\Pr_{w ← µ} [f + g = 0]`, подразумавая `\Pr_{w ← µ} [f(w) + g(w) = 0]`.

Если так, то я не могу понять, что должно значить это определение. К примеру, что имеется ввиду написанным под символами Pr в нём?

Иван

**Comment by avsmal** [comment]
Могут быть две различные случайные величины с одинаковым распределением.
Например, если мы кидаем игральную кость, то случайные величины X1 и X2,
равные 1, если выпал, соответсвенно, 1 и 2, и 0 в противном случае. У этих
двух случайных величин одинаковые распределения, но это разные случайные
величины. Поэтому понятие "случайная величина" и "вероятностное
распределение" не взаимозаменяемы. В конспекте могут быть некоторые вольности, но из
контекста должно быть всегда понятно, с чем мы имеем дело.

Теперь про конкретное определение. Есть общее вероятностное пространство,
относительно которого определены случайные величины. Относительно этого
пространства каждое событие вида "случайная величина X = x" имеет какую-то
вероятность. Это и определяет вероятностное распределение случайной величины. Под
знаком вероятности нужно указать общее вероятностное пространство.
В примере с кубиком выше под Pr нужно было бы указать, что вероятность
берётся про вероятностному пространству, которое соответствует броску
кубика.

Саша

**Comment by avsmal** [comment]
Посмотрел на реквест и понял, что я зря выше написал, что пространство общее. Оно не обязательно общее. В примере с кубиком было так, но в наших применениях есть два различный процесса: генерация равномерно случайно строки (условно подбрасыванием монетки) и генерация более короткой равномерно случайной строки с проследующим запуском алгоритма. По этому у каждого из символов вероятности своё вероятностное пространство. И они нигде не используется, в определении оно не требуется. Поэтому, ИМХО, добавлять для них буквы и добавлять в определение не стоит - только всех запутаем.

**Comment by avsmal** [comment]
То есть, вроде понятно:
- что такое статистически неразличимые *распределения*
- как по случайное величине построить её распределение.

Если у двух случайных величин получились статистически неразличимые распределения, то они тоже статистически неразличимы.
